/**
 * Antigravity PDF - Watermark Logic (Ultimate Clean Version)
 * Fixes: Doubling issue, Rotation mismatch, XFA compatibility, Image/Text Sync.
 */
document.addEventListener('DOMContentLoaded', () => {
    // UI Elements
    const fileInput = document.getElementById('watermarkFileInput');
    const uploadBtn = document.getElementById('btnUploadWatermark');
    const applyBtn = document.getElementById('btnApplyWatermark');
    const downloadBtn = document.getElementById('btnDownloadWatermark');
    const workspace = document.getElementById('watermarkWorkspace');
    const emptyState = document.getElementById('watermarkEmptyState');
    const previewContainer = document.getElementById('watermarkPreview');
    
    // Control Elements
    const wmText = document.getElementById('wmText');
    const wmSize = document.getElementById('wmSize'); 
    const wmColor = document.getElementById('wmColor');
    const wmOpacity = document.getElementById('wmOpacity');
    const wmRotation = document.getElementById('wmRotation');
    const wmImageInput = document.getElementById('wmImageInput');
    const imgOptions = document.getElementById('imgWatermarkOptions');
    const txtOptions = document.getElementById('txtWatermarkOptions');
    const wmPosX = document.getElementById('wmPosX');
    const wmPosY = document.getElementById('wmPosY');
    const wmScale = document.getElementById('wmScale');
    const wmFont = document.getElementById('wmFont');

    // State
    let currentFileData = null;     // Original bytes
    let watermarkedPdfBytes = null; // Generated bytes
    let watermarkType = 'text';     // Active mode
    let currentWatermarkImage = null; // Image array buffer
    let cachedBengaliFont = null;

    // History State for Undo/Reset
    let wmHistory = [];
    let isUndoing = false;
    const btnResetWatermark = document.getElementById('btnResetWatermark');
    const btnUndoWatermark = document.getElementById('btnUndoWatermark');

    function getWmState() {
        return {
            type: watermarkType,
            text: wmText.value,
            size: wmSize.value,
            color: wmColor.value,
            opacity: wmOpacity.value,
            rotation: wmRotation.value,
            posX: wmPosX.value,
            posY: wmPosY.value,
            scale: wmScale.value,
            font: wmFont.value,
            image: currentWatermarkImage
        };
    }

    function applyWmState(state) {
        if (!state) return;
        isUndoing = true;
        if (state.type !== watermarkType) window.toggleWatermarkType(state.type);
        wmText.value = state.text;
        wmSize.value = state.size;
        wmColor.value = state.color;
        wmOpacity.value = state.opacity;
        wmRotation.value = state.rotation;
        wmPosX.value = state.posX;
        wmPosY.value = state.posY;
        wmScale.value = state.scale;
        wmFont.value = state.font;
        currentWatermarkImage = state.image;
        updatePreview();
        isUndoing = false;
    }

    function pushWmState() {
        if (isUndoing) return;
        wmHistory.push(getWmState());
        if (wmHistory.length > 20) wmHistory.shift();
        if (btnUndoWatermark) btnUndoWatermark.disabled = false;
    }

    // Capture initial default state
    let defaultWmState = null;
    setTimeout(() => { if (wmText) defaultWmState = getWmState(); }, 500);

    if (btnResetWatermark) {
        btnResetWatermark.addEventListener('click', () => {
            if (!defaultWmState) return;
            pushWmState();
            applyWmState(defaultWmState);
        });
    }

    if (btnUndoWatermark) {
        btnUndoWatermark.addEventListener('click', () => {
            if (wmHistory.length > 0) {
                applyWmState(wmHistory.pop());
                if (wmHistory.length === 0) btnUndoWatermark.disabled = true;
            }
        });
    }

    if (!fileInput) return;

    // --- Tab Switching ---
    window.toggleWatermarkType = (type) => {
        watermarkType = type;
        const tabs = document.querySelectorAll('#watermarkWorkspace .tabs .btn');
        tabs.forEach(btn => btn.classList.remove('active'));
        if (type === 'text') {
            txtOptions.style.display = 'block';
            imgOptions.style.display = 'none';
            tabs[0].classList.add('active');
            if (document.getElementById('wmFontOption')) document.getElementById('wmFontOption').style.display = 'block';
        } else {
            txtOptions.style.display = 'none';
            imgOptions.style.display = 'block';
            tabs[1].classList.add('active');
            if (document.getElementById('wmFontOption')) document.getElementById('wmFontOption').style.display = 'none';
        }
        updatePreview();
    };

    // --- File Loading ---
    uploadBtn.addEventListener('click', () => fileInput.click());
    fileInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file || file.type !== 'application/pdf') return alert('Please select a valid PDF.');
        const reader = new FileReader();
        reader.onload = function() {
            currentFileData = new Uint8Array(this.result);
            watermarkedPdfBytes = null;
            downloadBtn.disabled = true;
            emptyState.classList.add('d-none');
            workspace.classList.remove('d-none');
            workspace.style.display = 'flex';
            updatePreview();
        };
        reader.readAsArrayBuffer(file);
    });

    wmImageInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = function() {
            pushWmState();
            currentWatermarkImage = new Uint8Array(this.result);
            updatePreview();
        };
        reader.readAsArrayBuffer(file);
    });

    // Event listeners for all controls
    [wmText, wmSize, wmColor, wmOpacity, wmRotation, wmPosX, wmPosY, wmScale, wmFont].forEach(el => {
        if (el) {
            el.addEventListener('input', updatePreview);
            el.addEventListener('change', pushWmState);
        }
    });

    // --- Preview Logic ---
    async function updatePreview() {
        if (!currentFileData) return;
        
        try {
            // ALWAYS preview the ORIGINAL data to avoid "doubling" effect
            const pdf = await pdfjsLib.getDocument({ data: currentFileData.slice(0) }).promise;
            const page = await pdf.getPage(1);
            const viewport = page.getViewport({ scale: 0.8 });

            const canvas = document.createElement('canvas');
            const ctx = canvas.getContext('2d');
            canvas.width = viewport.width;
            canvas.height = viewport.height;
            await page.render({ canvasContext: ctx, viewport }).promise;

            // Preview UI Overlay
            ctx.save();
            const x = canvas.width * (parseFloat(wmPosX.value) / 100);
            const y = canvas.height * (1 - (parseFloat(wmPosY.value) / 100)); // Canvas Y flip
            const scale = parseFloat(wmScale.value);
            const rotationRad = (parseInt(wmRotation.value) * Math.PI) / 180;
            
            ctx.translate(x, y);
            ctx.rotate(rotationRad);
            ctx.globalAlpha = parseFloat(wmOpacity.value);

            if (watermarkType === 'text') {
                const fontSize = parseInt(wmSize.value) * scale * 0.8;
                let fontStr = 'Outfit';
                if (wmFont.value === 'NotoSansBengali') fontStr = '"Noto Sans Bengali"';
                if (wmFont.value === 'HindSiliguri') fontStr = '"Hind Siliguri"';
                ctx.font = `bold ${fontSize}px ${fontStr}`;
                ctx.fillStyle = wmColor.value;
                ctx.textAlign = 'center';
                ctx.fillText(wmText.value, 0, 0);
            } else if (currentWatermarkImage) {
                const img = new Image();
                img.onload = () => {
                    const baseSize = 250;
                    const imgScale = (baseSize / Math.max(img.width, img.height)) * scale;
                    ctx.drawImage(img, -img.width * imgScale / 2, -img.height * imgScale / 2, img.width * imgScale, img.height * imgScale);
                    ctx.restore();
                };
                img.src = URL.createObjectURL(new Blob([currentWatermarkImage]));
                previewContainer.innerHTML = '';
                previewContainer.appendChild(canvas);
                return;
            }
            ctx.restore();
            previewContainer.innerHTML = '';
            previewContainer.appendChild(canvas);
        } catch (e) { console.error('Preview error', e); }
    }

    // --- Apply Logic ---
    applyBtn.addEventListener('click', async () => {
        if (!currentFileData) return;
        applyBtn.disabled = true;
        applyBtn.innerHTML = '<i data-lucide="loader-2" class="spin"></i> Processing...';
        if (window.lucide) lucide.createIcons();

        try {
            const { PDFDocument, rgb, degrees } = PDFLib;
            const pdf = await pdfjsLib.getDocument({ data: currentFileData.slice(0) }).promise;
            const newPdf = await PDFDocument.create();
            newPdf.registerFontkit(fontkit);

            // Determine Font & Embedding
            let font = await newPdf.embedFont(PDFLib.StandardFonts.HelveticaBold);
            if (watermarkType === 'text' && wmFont.value !== 'Helvetica-Bold') {
                if (!cachedBengaliFont) {
                    const res = await fetch('https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansBengali/NotoSansBengali-Regular.ttf');
                    cachedBengaliFont = await res.arrayBuffer();
                }
                font = await newPdf.embedFont(cachedBengaliFont);
            }

            // Embedding Image
            let wmImg = null;
            if (watermarkType === 'image' && currentWatermarkImage) {
                const head = currentWatermarkImage.slice(0, 4);
                const isPng = head[0] === 0x89 && head[1] === 0x50;
                wmImg = isPng ? await newPdf.embedPng(currentWatermarkImage) : await newPdf.embedJpg(currentWatermarkImage);
            }

            // Processing Pages (Nuclear Flattening)
            for (let i = 1; i <= pdf.numPages; i++) {
                applyBtn.innerHTML = `Processing ${i}/${pdf.numPages}...`;
                const page = await pdf.getPage(i);
                const scaleF = 2.0; 
                const vp = page.getViewport({ scale: scaleF });
                const can = document.createElement('canvas');
                can.width = vp.width; can.height = vp.height;
                await page.render({ canvasContext: can.getContext('2d'), viewport: vp }).promise;
                
                const imgData = can.toDataURL('image/jpeg', 0.9);
                const embeddedPage = await newPdf.embedJpg(imgData);
                const newPage = newPdf.addPage([vp.width / scaleF, vp.height / scaleF]);
                const { width, height } = newPage.getSize();
                newPage.drawImage(embeddedPage, { x: 0, y: 0, width, height });

                // POSITIONING MATH (Center Sync)
                const opacity = parseFloat(wmOpacity.value);
                const rot = parseInt(wmRotation.value);
                const scaleVal = parseFloat(wmScale.value);
                const xCtr = width * (parseFloat(wmPosX.value) / 100);
                const yCtr = height * (parseFloat(wmPosY.value) / 100);
                // Important: PDF-Lib rotation is counter-clockwise, negate angle to match Canvas clockwise
                const pdfRot = degrees(-rot); 
                const rad = (-rot * Math.PI) / 180;

                if (watermarkType === 'text') {
                    const fSize = parseInt(wmSize.value) * scaleVal;
                    const tw = font.widthOfTextAtSize(wmText.value, fSize);
                    const offX = (tw / 2) * Math.cos(rad);
                    const offY = (tw / 2) * Math.sin(rad);
                    newPage.drawText(wmText.value, { x: xCtr - offX, y: yCtr - offY, size: fSize, font, color: hexToRgbLib(wmColor.value, rgb), opacity, rotate: pdfRot });
                } else if (wmImg) {
                    const imgDims = wmImg.scale(0.5 * scaleVal);
                    const iw = imgDims.width; const ih = imgDims.height;
                    const sX = xCtr - (iw/2 * Math.cos(rad) - ih/2 * Math.sin(rad));
                    const sY = yCtr - (iw/2 * Math.sin(rad) + ih/2 * Math.cos(rad));
                    newPage.drawImage(wmImg, { x: sX, y: sY, width: iw, height: ih, opacity, rotate: pdfRot });
                }
            }

            watermarkedPdfBytes = await newPdf.save({ useObjectStreams: false });
            alert('Processing Complete!');
            downloadBtn.disabled = false;
        } catch (err) {
            console.error(err);
            alert('Error: ' + err.message);
        } finally {
            applyBtn.disabled = false;
            applyBtn.innerHTML = '<i data-lucide="zap"></i> Apply Watermark';
            if (window.lucide) lucide.createIcons();
        }
    });

    downloadBtn.addEventListener('click', () => {
        if (!watermarkedPdfBytes) return;
        const blob = new Blob([watermarkedPdfBytes], { type: 'application/pdf' });
        const name = (fileInput.files[0] ? fileInput.files[0].name.replace('.pdf', '') : 'result') + '_watermarked.pdf';
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a'); a.href = url; a.download = name;
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
    });

    function hexToRgbLib(hex, rgbFunc) {
        const r = parseInt(hex.slice(1, 3), 16) / 255;
        const g = parseInt(hex.slice(3, 5), 16) / 255;
        const b = parseInt(hex.slice(5, 7), 16) / 255;
        return rgbFunc(r, g, b);
    }
});
